const coverPalette = [
  ["#1f1c1a", "#7a6a4f"],
  ["#141312", "#3d3a36"],
  ["#221f1a", "#8f7a55"],
  ["#0f1011", "#4b4a46"],
  ["#1b1815", "#6a5b44"],
  ["#121415", "#5e5649"],
];

const makeCoverDataUrl = (artist, album, seed = 0) => {
  const [c1, c2] = coverPalette[seed % coverPalette.length];
  const svg = `
    <svg xmlns="http://www.w3.org/2000/svg" width="640" height="640">
      <defs>
        <linearGradient id="g" x1="0" x2="1" y1="0" y2="1">
          <stop offset="0%" stop-color="${c1}" />
          <stop offset="100%" stop-color="${c2}" />
        </linearGradient>
      </defs>
      <rect width="100%" height="100%" fill="url(#g)" />
      <rect x="40" y="40" width="560" height="560" rx="14" ry="14" fill="none" stroke="#f1efea" stroke-opacity="0.2" stroke-width="2" />
      <text x="70" y="140" fill="#f1efea" font-family="Cormorant Garamond" font-size="40" font-weight="600">Ziggy Play</text>
      <text x="70" y="210" fill="#f1efea" font-family="Inter" font-size="20" font-weight="400">${artist}</text>
      <text x="70" y="250" fill="#f1efea" font-family="Inter" font-size="18" font-weight="300">${album}</text>
      <text x="70" y="530" fill="#f1efea" font-family="Inter" font-size="14" font-weight="300" opacity="0.7">Coleção privada</text>
      <text x="70" y="560" fill="#f1efea" font-family="Inter" font-size="14" font-weight="300" opacity="0.7">Pressagem selecionada</text>
    </svg>
  `;
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg.trim())}`;
};

export const partners = [
  {
    id: "p1",
    name: "Casa Audionauta",
    url: "https://casaudionauta.com",
    description: "Curadoria focada em prensagens originais e edições audiophile.",
    address: "Rua das Agulhas, 82 · Pinheiros · São Paulo",
  },
  {
    id: "p2",
    name: "Rota do Vinil",
    url: "https://rotadovinil.com",
    description: "Acervo amplo com raridades brasileiras e importados clássicos.",
    address: "Av. Aurora, 155 · Centro · São Paulo",
  },
  {
    id: "p3",
    name: "Selo Sonoro",
    url: "https://selosonoro.com",
    description: "Seleção de dub, soul e new wave com foco em condição premium.",
    address: "Rua do Som, 41 · Santa Cecilia · São Paulo",
  },
];

export const vinyls = [
  {
    id: "v1",
    artist: "Marvin Gaye",
    album: "I Want You",
    year: 1976,
    genre: "Soul",
    format: "LP 12\"",
    cover_image_url: "https://upload.wikimedia.org/wikipedia/en/e/e3/Marvin-gaye-i-want-you.jpg",
    tags: ["Soul de quarto escuro", "Groove lento e urbano"],
    description:
      "Soul noturno com grooves lentos e sintetizadores suaves. Um disco de desejo e atmosfera cinematografica.",
    tracklist: [
      "I Want You (vocal)",
      "Come Live with Me Angel",
      "After the Dance (instrumental)",
      "Feel All My Love Inside",
      "I Wanna Be Where You Are",
      "I Want You (intro jam)",
      "All the Way Around",
      "Since I Had You",
      "Soon I'll Be Loving You Again",
      "I Want You (jam)",
      "After the Dance (vocal)",
    ],
    tech: {
      label: "Tamla",
      producer: "Marvin Gaye, Leon Ware, Arthur \"T-Boy\" Ross",
      studio: "Marvin's Room; Hitsville West (Los Angeles)",
      country: "EUA",
    },
  },
  {
    id: "v2",
    artist: "Sade",
    album: "Diamond Life",
    year: 1984,
    genre: "Soul",
    format: "LP 12\"",
    cover_image_url: "https://upload.wikimedia.org/wikipedia/en/6/69/Sade_-_Diamond_Life.png",
    tags: ["Soul de quarto escuro", "Baladas com arranjo orquestral"],
    description:
      "Soul sofisticado, frio e elegante. Baixo macio, voz central e arranjos que respiram.",
    tracklist: [
      "Smooth Operator",
      "Your Love Is King",
      "Hang On to Your Love",
      "Frankie's First Affair",
      "When Am I Going to Make a Living",
      "Cherry Pie",
      "Sally",
      "I Will Be Your Friend",
      "Why Can't We Live Together",
    ],
    tech: {
      label: "Epic",
      producer: "Robin Millar",
      studio: "Power Plant (London)",
      country: "Reino Unido",
    },
  },
  {
    id: "v3",
    artist: "Isaac Hayes",
    album: "Hot Buttered Soul",
    year: 1969,
    genre: "Soul",
    format: "LP 12\"",
    cover_image_url:
      "https://upload.wikimedia.org/wikipedia/en/8/86/Isaac_Hayes%2C_Hot_Buttered_Soul_Album_Cover.jpg",
    tags: ["Baladas com arranjo orquestral", "Groove lento e urbano"],
    description:
      "Soul expansivo em quatro faixas longas. Arranjos orquestrais e groove denso.",
    tracklist: ["Walk On By", "Hyperbolicsyllabicsesquedalymistic", "One Woman", "By the Time I Get to Phoenix"],
    tech: {
      label: "Enterprise",
      producer: "Al Bell, Marvell Thomas, Allen Jones",
      studio: "Ardent (Memphis); Tera Shirma (Detroit)",
      country: "EUA",
    },
  },
  {
    id: "v4",
    artist: "Donny Hathaway",
    album: "Donny Hathaway",
    year: 1971,
    genre: "Soul",
    format: "LP 12\"",
    cover_image_url: "https://upload.wikimedia.org/wikipedia/en/6/62/Donny_Hathaway_album.jpg",
    tags: ["Soul de quarto escuro", "Baladas com arranjo orquestral"],
    description:
      "Interpretações soul intensas, voz quente e arranjos elegantes. Clima de igreja vazia depois do culto.",
    tracklist: [
      "Giving Up",
      "A Song for You",
      "Little Girl",
      "He Ain't Heavy, He's My Brother",
      "Magnificent Sanctuary Band",
      "She Is My Lady",
      "I Believe in Music",
      "Take a Love Song",
      "Put Your Hand in the Hand",
    ],
    tech: {
      label: "Atco",
      producer: "Jerry Wexler, Arif Mardin, Donny Hathaway",
      studio: "Atlantic (New York); Criteria (Miami); Universal (Chicago)",
      country: "EUA",
    },
  },
  {
    id: "v5",
    artist: "Milton Nascimento & Lô Borges",
    album: "Clube da Esquina",
    year: 1972,
    genre: "MPB",
    format: "LP 12\"",
    cover_image_url: "https://upload.wikimedia.org/wikipedia/en/7/74/Clubedaesquinacover.png",
    tags: ["Tropicalia tardia", "Corais de varanda"],
    description:
      "Duplo LP de cancoes solares e melancolicas. Harmonia brasileira, violao e coro coletivo.",
    tracklist: [
      "Tudo Que Você Podia Ser",
      "Cais",
      "O Trem Azul",
      "Saídas e Bandeiras Nº 1",
      "Nuvem Cigana",
      "Cravo e Canela",
      "Dos Cruces",
      "Um Girassol Da Cor De Seu Cabelo",
      "San Vicente",
      "Estrelas",
      "Clube da Esquina Nº 2",
      "Paisagem Da Janela",
      "Me Deixa Em Paz",
      "Os Povos",
      "Saídas e Bandeiras Nº 2",
      "Um Gosto De Sol",
      "Pelo Amor De Deus",
      "Lilia",
      "Trem De Doido",
      "Nada Será Como Antes",
      "Ao Que Vai Nascer",
    ],
    tech: {
      label: "EMI-Odeon",
      producer: "Milton Miranda, Lindolfo Gaya",
      studio: "Piratininga Beach (Niterói); Odeon (Rio de Janeiro)",
      country: "Brasil",
    },
  },
  {
    id: "v6",
    artist: "Caetano Veloso",
    album: "Transa",
    year: 1972,
    genre: "MPB",
    format: "LP 12\"",
    cover_image_url: "https://upload.wikimedia.org/wikipedia/en/f/ff/Transa.jpg",
    tags: ["Tropicalia tardia", "Samba de estrada"],
    description:
      "Gravado em exílio, mistura ingles e português com blues e samba. Um disco livre e aberto.",
    tracklist: [
      "You Don't Know Me",
      "Nine Out of Ten",
      "Triste Bahia",
      "It's a Long Way",
      "Mora na Filosofia",
      "Neolithic Man",
      "Nostalgia (That's What Rock'n Roll Is All About)",
    ],
    tech: {
      label: "Philips",
      producer: "Ralph Mace",
      studio: "Londres (exílio)",
      country: "Reino Unido",
    },
  },
  {
    id: "v7",
    artist: "Novos Baianos",
    album: "Acabou Chorare",
    year: 1972,
    genre: "MPB",
    format: "LP 12\"",
    cover_image_url: "https://upload.wikimedia.org/wikipedia/en/9/93/Album_Acabou_chorare_cover.jpg",
    tags: ["Samba de estrada", "Corais de varanda"],
    description:
      "Samba rock e psicodelia leve. Violao, coro e alegria com a cara de 1972.",
    tracklist: [
      "Brasil Pandeiro",
      "Preta Pretinha",
      "Tinindo, Trincando",
      "Swing de Campo Grande",
      "Acabou Chorare",
      "Mistério do Planeta",
      "A Menina Dança",
      "Besta É Tu",
      "Um Bilhete Pra Didi",
      "Preta Pretinha (reprise)",
    ],
    tech: {
      label: "Som Livre",
      producer: "Eustáquio Sena, João Araújo",
      studio: "Cantinho do Vovô (Rio de Janeiro)",
      country: "Brasil",
    },
  },
  {
    id: "v8",
    artist: "Jorge Ben",
    album: "A Tábua de Esmeralda",
    year: 1974,
    genre: "MPB",
    format: "LP 12\"",
    cover_image_url: "https://upload.wikimedia.org/wikipedia/en/9/9d/AT%C3%A1buaDeEsmeralda.jpg",
    tags: ["Tropicalia tardia", "Samba de estrada"],
    description:
      "Samba funk alquímico com guitarras secas e letras místicas. Groove hipnótico.",
    tracklist: [
      "Os alquimistas estão chegando os alquimistas",
      "O homem da gravata florida",
      "Errare humanum est",
      "Menina mulher da pele preta",
      "Eu vou torcer",
      "Magnólia",
      "Minha teimosia, uma arma pra te conquistar",
      "Zumbi",
      "Brother",
      "O namorado da viúva",
      "Hermes Trismegisto e sua celeste tábua de esmeralda",
      "Cinco minutos",
    ],
    tech: {
      label: "Philips",
      producer: "Paulinho Tapajós",
      studio: null,
      country: "Brasil",
    },
  },
  {
    id: "v9",
    artist: "Joy Division",
    album: "Unknown Pleasures",
    year: 1979,
    genre: "Post-punk / New wave",
    format: "LP 12\"",
    cover_image_url: "https://upload.wikimedia.org/wikipedia/en/5/5a/UnknownPleasuresVinyl.jpg",
    tags: ["Alternative Punk", "Pistas minimalistas"],
    description:
      "Baixo frio, bateria seca e vocais distantes. Um disco de sombra e espaco.",
    tracklist: [
      "Disorder",
      "Day of the Lords",
      "Candidate",
      "Insight",
      "New Dawn Fades",
      "She's Lost Control",
      "Shadowplay",
      "Wilderness",
      "Interzone",
      "I Remember Nothing",
    ],
    tech: {
      label: "Factory",
      producer: "Martin Hannett",
      studio: "Strawberry (Stockport, UK)",
      country: "Reino Unido",
    },
  },
  {
    id: "v10",
    artist: "Talking Heads",
    album: "Remain in Light",
    year: 1980,
    genre: "Post-punk / New wave",
    format: "LP 12\"",
    cover_image_url: "https://upload.wikimedia.org/wikipedia/en/2/2d/TalkingHeadsRemaininLight.jpg",
    tags: ["Alternative Punk", "Pistas minimalistas"],
    description:
      "Polirritmia, loops e funk nervoso. Um classico que mistura rock e Africa.",
    tracklist: [
      "Born Under Punches (The Heat Goes On)",
      "Crosseyed and Painless",
      "The Great Curve",
      "Once in a Lifetime",
      "Houses in Motion",
      "Seen and Not Seen",
      "Listening Wind",
      "The Overload",
    ],
    tech: {
      label: "Sire",
      producer: "Brian Eno",
      studio: "Compass Point (Nassau); Sigma Sound (New York City)",
      country: "EUA",
    },
  },
  {
    id: "v11",
    artist: "Kraftwerk",
    album: "Computer World",
    year: 1981,
    genre: "Post-punk / New wave",
    format: "LP 12\"",
    cover_image_url: "https://upload.wikimedia.org/wikipedia/en/a/a6/Kraftwerk_-_Computer_World.png",
    tags: ["Sintetizadores frios", "Pistas minimalistas"],
    description:
      "Eletronica minimalista sobre tecnologia e vida digital. Frio, preciso, perfeito.",
    tracklist: [
      "Computer World",
      "Pocket Calculator",
      "Numbers",
      "Computer World 2",
      "Computer Love",
      "Home Computer",
      "It's More Fun to Compute",
    ],
    tech: {
      label: "Kling Klang; EMI Electrola",
      producer: "Ralf Hütter, Florian Schneider",
      studio: "Kling Klang (Düsseldorf)",
      country: "Alémanha",
    },
  },
  {
    id: "v12",
    artist: "New Order",
    album: "Power, Corruption & Lies",
    year: 1983,
    genre: "Post-punk / New wave",
    format: "LP 12\"",
    cover_image_url:
      "https://upload.wikimedia.org/wikipedia/commons/4/4f/New_Order_-_Power%2C_Corruption_%26_Lies.png",
    tags: ["Alternative Punk", "Sintetizadores frios"],
    description:
      "Sintetizadores e baixo elastico. Pop frio com pulso de pista.",
    tracklist: [
      "Age of Consent",
      "We All Stand",
      "The Village",
      "5 8 6",
      "Your Silent Face",
      "Ultraviolence",
      "Ecstasy",
      "Leave Me Alone",
    ],
    tech: {
      label: "Factory",
      producer: "New Order",
      studio: "Britannia Row (Islington)",
      country: "Reino Unido",
    },
  },
  {
    id: "v13",
    artist: "Augustus Pablo",
    album: "King Tubbys Meets Rockers Uptown",
    year: 1976,
    genre: "Dub",
    format: "LP 12\"",
    cover_image_url:
      "https://upload.wikimedia.org/wikipedia/en/c/c7/AugustusPablo-KingTubbyMeetsRockersUptown.jpg",
    tags: ["Dub de porao", "Ecos analogicos"],
    description:
      "Dub classico com melodica e ecos profundos. Atmosfera quente e analogica.",
    tracklist: [
      "Keep On Dubbing",
      "Stop Them Jah",
      "Young Generation Dub",
      "Each One Dub",
      "555 Dub Street",
      "Braces Tower Dub",
      "King Tubby Meets Rockers Uptown",
      "Corner Crew Dub",
      "Say So",
      "Skanking Dub",
      "Frozen Dub",
      "Satta Dub",
    ],
    tech: {
      label: "Yard International; Clocktower",
      producer: "Horace Swaby",
      studio: "Randy's (Kingston); King Tubby's (Kingston 11)",
      country: "Jamaica",
    },
  },
  {
    id: "v14",
    artist: "The Upsetters",
    album: "Super Ape",
    year: 1976,
    genre: "Dub",
    format: "LP 12\"",
    cover_image_url: "https://upload.wikimedia.org/wikipedia/en/4/46/TheUpsetters-SuperApe.jpg",
    tags: ["Dub de porao", "Ecos analogicos"],
    description:
      "Dub psicodelico de Black Ark. Baixos gordos e texturas de fita.",
    tracklist: [
      "Zion's Blood",
      "Croaking Lizard",
      "Black Vest",
      "Underground",
      "Curly Dub",
      "Dread Lion",
      "Three in One",
      "Patience",
      "Dub Along",
      "Super Ape",
    ],
    tech: {
      label: "Island; Upsetter",
      producer: "Lee Perry",
      studio: "Black Ark (Kingston)",
      country: "Jamaica",
    },
  },
  {
    id: "v15",
    artist: "The Upsetters",
    album: "Return of the Super Ape",
    year: 1978,
    genre: "Dub",
    format: "LP 12\"",
    cover_image_url: "https://upload.wikimedia.org/wikipedia/en/6/6f/TheUpsetters-ReturnOfTheSuperApe.jpg",
    tags: ["Dub de porao", "Ritmos de sound system"],
    description:
      "Dub denso e cavernoso, ultima fase do Black Ark. Ecos longos e bateria seca.",
    tracklist: [
      "Dyon Anaswa",
      "Return of the Super Ape",
      "Tell Me Something Good",
      "Bird in Hand",
      "Crab Yars",
      "Jah Jah Ah Natty Dread",
      "Psycha & Trim",
      "The Lion",
      "Huzza a Hana",
      "High Ranking Sammy",
    ],
    tech: {
      label: "Lion of Judah",
      producer: "Lee Perry",
      studio: "Black Ark (Kingston)",
      country: "Jamaica",
    },
  },
  {
    id: "v16",
    artist: "Scientist",
    album: "Scientist Rids the World of the Evil Curse of the Vampires",
    year: 1981,
    genre: "Dub",
    format: "LP 12\"",
    cover_image_url: "https://upload.wikimedia.org/wikipedia/en/7/79/Scientist-RidsTheWorld.jpg",
    tags: ["Ecos analogicos", "Ritmos de sound system"],
    description:
      "Dub cinematografico com titulos de filme B. Grave profundo e mix fantasma.",
    tracklist: [
      "Voodoo Curse",
      "Dance of the Vampires",
      "Blood On His Lips",
      "Cry of the Werewolf",
      "The Mummy's Shroud",
      "The Corpse Rises",
      "Night of the Living Dead",
      "Your Teeth In My Neck",
      "Plague of Zombies",
      "Ghost of Frankenstein",
    ],
    tech: {
      label: "Greensleeves",
      producer: "Henry \"Junjo\" Lawes",
      studio: "Channel One Studios (Kingston)",
      country: "Jamaica",
    },
  },
];

export const inventory = [
  {
    vinyl_id: "v1",
    partner_id: "p1",
    price_normal: 210,
    price_member: 178,
    condition_media: "NM",
    condition_sleeve: "VG+",
    availability_status: "Disponivel",
    quantity: 1,
    cover_image_url: vinyls[0].cover_image_url,
    product_url: "https://casaudionauta.com/ziggy/i-want-you",
    notes: "Prensagem original, encarte presente",
  },
  {
    vinyl_id: "v2",
    partner_id: "p3",
    price_normal: 195,
    price_member: 175,
    condition_media: "VG+",
    condition_sleeve: "VG",
    availability_status: "Disponivel",
    quantity: 2,
    cover_image_url: vinyls[1].cover_image_url,
    product_url: "https://selosonoro.com/ziggy/diamond-life",
    notes: "Capa com leve desgaste",
  },
  {
    vinyl_id: "v3",
    partner_id: "p2",
    price_normal: 220,
    price_member: 198,
    condition_media: "VG+",
    condition_sleeve: "VG+",
    availability_status: "Disponivel",
    quantity: 1,
    cover_image_url: vinyls[2].cover_image_url,
    product_url: "https://rotadovinil.com/ziggy/hot-buttered-soul",
    notes: "Pressagem 70s",
  },
  {
    vinyl_id: "v4",
    partner_id: "p1",
    price_normal: 190,
    price_member: 165,
    condition_media: "NM",
    condition_sleeve: "VG+",
    availability_status: "Disponivel",
    quantity: 1,
    cover_image_url: vinyls[3].cover_image_url,
    product_url: "https://casaudionauta.com/ziggy/donny-hathaway",
    notes: "Sleeve texturizado",
  },
  {
    vinyl_id: "v5",
    partner_id: "p2",
    price_normal: 210,
    price_member: 188,
    condition_media: "NM",
    condition_sleeve: "VG+",
    availability_status: "Disponivel",
    quantity: 1,
    cover_image_url: vinyls[4].cover_image_url,
    product_url: "https://rotadovinil.com/ziggy/clube-da-esquina",
    notes: "Duplo LP",
  },
  {
    vinyl_id: "v6",
    partner_id: "p1",
    price_normal: 185,
    price_member: 162,
    condition_media: "VG+",
    condition_sleeve: "VG+",
    availability_status: "Disponivel",
    quantity: 1,
    cover_image_url: vinyls[5].cover_image_url,
    product_url: "https://casaudionauta.com/ziggy/transa",
    notes: "Pressagem brasileira",
  },
  {
    vinyl_id: "v7",
    partner_id: "p3",
    price_normal: 170,
    price_member: 150,
    condition_media: "VG+",
    condition_sleeve: "VG",
    availability_status: "Disponivel",
    quantity: 2,
    cover_image_url: vinyls[6].cover_image_url,
    product_url: "https://selosonoro.com/ziggy/acabou-chorare",
    notes: "Reedicao clássica",
  },
  {
    vinyl_id: "v8",
    partner_id: "p2",
    price_normal: 200,
    price_member: 178,
    condition_media: "NM",
    condition_sleeve: "VG+",
    availability_status: "Disponivel",
    quantity: 1,
    cover_image_url: vinyls[7].cover_image_url,
    product_url: "https://rotadovinil.com/ziggy/tabua-de-esmeralda",
    notes: "Capa dupla",
  },
  {
    vinyl_id: "v9",
    partner_id: "p3",
    price_normal: 195,
    price_member: 172,
    condition_media: "NM",
    condition_sleeve: "VG+",
    availability_status: "Disponivel",
    quantity: 2,
    cover_image_url: vinyls[8].cover_image_url,
    product_url: "https://selosonoro.com/ziggy/unknown-pleasures",
    notes: "Pressagem UK",
  },
  {
    vinyl_id: "v10",
    partner_id: "p1",
    price_normal: 205,
    price_member: 182,
    condition_media: "NM",
    condition_sleeve: "VG+",
    availability_status: "Disponivel",
    quantity: 1,
    cover_image_url: vinyls[9].cover_image_url,
    product_url: "https://casaudionauta.com/ziggy/remain-in-light",
    notes: "Sleeve original",
  },
  {
    vinyl_id: "v11",
    partner_id: "p2",
    price_normal: 215,
    price_member: 190,
    condition_media: "VG+",
    condition_sleeve: "VG+",
    availability_status: "Disponivel",
    quantity: 1,
    cover_image_url: vinyls[10].cover_image_url,
    product_url: "https://rotadovinil.com/ziggy/computer-world",
    notes: "Pressagem alema",
  },
  {
    vinyl_id: "v12",
    partner_id: "p1",
    price_normal: 198,
    price_member: 176,
    condition_media: "VG+",
    condition_sleeve: "VG+",
    availability_status: "Disponivel",
    quantity: 1,
    cover_image_url: vinyls[11].cover_image_url,
    product_url: "https://casaudionauta.com/ziggy/power-corruption-lies",
    notes: "Capa sem texto",
  },
  {
    vinyl_id: "v13",
    partner_id: "p2",
    price_normal: 175,
    price_member: 155,
    condition_media: "VG+",
    condition_sleeve: "VG",
    availability_status: "Disponivel",
    quantity: 1,
    cover_image_url: vinyls[12].cover_image_url,
    product_url: "https://rotadovinil.com/ziggy/king-tubby-meets-rockers-uptown",
    notes: "Dub classico",
  },
  {
    vinyl_id: "v14",
    partner_id: "p3",
    price_normal: 180,
    price_member: 160,
    condition_media: "VG+",
    condition_sleeve: "VG+",
    availability_status: "Disponivel",
    quantity: 1,
    cover_image_url: vinyls[13].cover_image_url,
    product_url: "https://selosonoro.com/ziggy/super-ape",
    notes: "Black Ark",
  },
  {
    vinyl_id: "v15",
    partner_id: "p1",
    price_normal: 185,
    price_member: 165,
    condition_media: "VG+",
    condition_sleeve: "VG",
    availability_status: "Disponivel",
    quantity: 1,
    cover_image_url: vinyls[14].cover_image_url,
    product_url: "https://casaudionauta.com/ziggy/return-of-the-super-ape",
    notes: "Capa assinada",
  },
  {
    vinyl_id: "v16",
    partner_id: "p2",
    price_normal: 170,
    price_member: 150,
    condition_media: "VG",
    condition_sleeve: "VG",
    availability_status: "Disponivel",
    quantity: 1,
    cover_image_url: vinyls[15].cover_image_url,
    product_url: "https://rotadovinil.com/ziggy/scientist-vampires",
    notes: "Greensleeves",
  },
];

export const sessions = [
  {
    id: "s1",
    date: "2026-02-13",
    theme: "Noir Soul",
    description:
      "Texturas cinematograficas, vozes densas e groove lento para abrir a sala.",
    movements: ["Soul de quarto escuro", "Baladas com arranjo orquestral", "Groove lento e urbano"],
  },
  {
    id: "s2",
    date: "2026-02-15",
    theme: "Brasilidade Cosmica",
    description:
      "MPB solar com psicodelia, samba torto e harmonias que abrem espaco.",
    movements: ["Tropicalia tardia", "Samba de estrada", "Corais de varanda"],
  },
  {
    id: "s3",
    date: "2026-02-18",
    theme: "Minimal Pulse",
    description:
      "Post-punk e new wave em repeticao hipnotica, linhas frias e pulsos secos.",
    movements: ["Alternative Punk", "Sintetizadores frios", "Pistas minimalistas"],
  },
  {
    id: "s4",
    date: "2026-02-20",
    theme: "Dub & Terras",
    description:
      "Graves profundos, ecos longos e poeira quente. Uma noite de dub roots.",
    movements: ["Dub de porao", "Ecos analogicos", "Ritmos de sound system"],
  },
  {
    id: "s5",
    date: "2026-02-22",
    theme: "Groove Urbano",
    description: "Baixos marcados e camadas de soul moderno.",
    movements: ["Groove lento e urbano", "Soul de quarto escuro", "Baladas com arranjo orquestral"],
  },
  {
    id: "s6",
    date: "2026-02-25",
    theme: "Ritual Tropical",
    description: "Samba psicodelico e harmonias abertas.",
    movements: ["Tropicalia tardia", "Samba de estrada", "Corais de varanda"],
  },
  {
    id: "s7",
    date: "2026-02-27",
    theme: "Circuito Frio",
    description: "Sintetizadores gelados e batidas minimalistas.",
    movements: ["Sintetizadores frios", "Pistas minimalistas", "Alternative Punk"],
  },
  {
    id: "s8",
    date: "2026-03-01",
    theme: "Ecos do Porao",
    description: "Dub denso com texturas analogicas.",
    movements: ["Dub de porao", "Ecos analogicos", "Ritmos de sound system"],
  },
];

export const sessionVinyl = [
  { session_id: "s1", vinyl_id: "v1", context_type: "tocado" },
  { session_id: "s1", vinyl_id: "v2", context_type: "tocado" },
  { session_id: "s1", vinyl_id: "v3", context_type: "tocado" },
  { session_id: "s1", vinyl_id: "v4", context_type: "tocado" },
  { session_id: "s1", vinyl_id: "v10", context_type: "relacionado" },
  { session_id: "s1", vinyl_id: "v12", context_type: "relacionado" },
  { session_id: "s2", vinyl_id: "v5", context_type: "tocado" },
  { session_id: "s2", vinyl_id: "v6", context_type: "tocado" },
  { session_id: "s2", vinyl_id: "v7", context_type: "tocado" },
  { session_id: "s2", vinyl_id: "v8", context_type: "tocado" },
  { session_id: "s2", vinyl_id: "v9", context_type: "relacionado" },
  { session_id: "s2", vinyl_id: "v11", context_type: "relacionado" },
  { session_id: "s3", vinyl_id: "v9", context_type: "tocado" },
  { session_id: "s3", vinyl_id: "v10", context_type: "tocado" },
  { session_id: "s3", vinyl_id: "v11", context_type: "tocado" },
  { session_id: "s3", vinyl_id: "v12", context_type: "tocado" },
  { session_id: "s3", vinyl_id: "v3", context_type: "relacionado" },
  { session_id: "s3", vinyl_id: "v13", context_type: "relacionado" },
  { session_id: "s4", vinyl_id: "v13", context_type: "tocado" },
  { session_id: "s4", vinyl_id: "v14", context_type: "tocado" },
  { session_id: "s4", vinyl_id: "v15", context_type: "tocado" },
  { session_id: "s4", vinyl_id: "v16", context_type: "tocado" },
  { session_id: "s4", vinyl_id: "v7", context_type: "relacionado" },
  { session_id: "s4", vinyl_id: "v8", context_type: "relacionado" },
  { session_id: "s5", vinyl_id: "v1", context_type: "tocado" },
  { session_id: "s5", vinyl_id: "v2", context_type: "tocado" },
  { session_id: "s5", vinyl_id: "v4", context_type: "tocado" },
  { session_id: "s5", vinyl_id: "v6", context_type: "tocado" },
  { session_id: "s5", vinyl_id: "v3", context_type: "relacionado" },
  { session_id: "s5", vinyl_id: "v5", context_type: "relacionado" },
  { session_id: "s6", vinyl_id: "v5", context_type: "tocado" },
  { session_id: "s6", vinyl_id: "v7", context_type: "tocado" },
  { session_id: "s6", vinyl_id: "v8", context_type: "tocado" },
  { session_id: "s6", vinyl_id: "v6", context_type: "tocado" },
  { session_id: "s6", vinyl_id: "v2", context_type: "relacionado" },
  { session_id: "s6", vinyl_id: "v9", context_type: "relacionado" },
  { session_id: "s7", vinyl_id: "v9", context_type: "tocado" },
  { session_id: "s7", vinyl_id: "v10", context_type: "tocado" },
  { session_id: "s7", vinyl_id: "v11", context_type: "tocado" },
  { session_id: "s7", vinyl_id: "v12", context_type: "tocado" },
  { session_id: "s7", vinyl_id: "v3", context_type: "relacionado" },
  { session_id: "s7", vinyl_id: "v14", context_type: "relacionado" },
  { session_id: "s8", vinyl_id: "v13", context_type: "tocado" },
  { session_id: "s8", vinyl_id: "v14", context_type: "tocado" },
  { session_id: "s8", vinyl_id: "v15", context_type: "tocado" },
  { session_id: "s8", vinyl_id: "v16", context_type: "tocado" },
  { session_id: "s8", vinyl_id: "v10", context_type: "relacionado" },
  { session_id: "s8", vinyl_id: "v12", context_type: "relacionado" },
];
